make WfEngineConfig.namespace required
when it is not set, we get:

File "/code/app/services/wf_engines/argo_engine.py", line 20, in __init__
self.api_endpoint = (vl_config.wf_engine_config.api_endpoint +
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     "api/v1/workflows/" +
                     ~~~~~~~~~~~~~~~~~~~~^
                     vl_config.wf_engine_config.namespace)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str