remove ggshield from conda environment to fix build
It was causing an error when building installing the conda environment
in the Dockerfile:

PackagesNotFoundError: The following packages are not available from current channels: ggshield. Current channels: https://conda.anaconda.org/conda-forge